# Action1：数据集：porto seguro safe driver prediction（kaggle 2017年比赛）
https://www.kaggle.com/c/porto-seguro-safe-driver-prediction/data
Porto Seguro是巴西最大的汽车与住房保险公司之一，根据汽车保单持有人的数据建立机器学习模型，分析该持有人是否会在次年提出索赔。数据已进行脱敏
使用GBDT+LR模型进行预测，并计算Normalized Cross Entropy

In [1]:
import pandas as pd

data_train = pd.read_csv('/Users/huangzhan/Documents/开课吧/RS/Chap3.6-Learning to Rank与Airbnb个性化推荐/L10/Action1/train.csv')
data_test = pd.read_csv('/Users/huangzhan/Documents/开课吧/RS/Chap3.6-Learning to Rank与Airbnb个性化推荐/L10/Action1/test.csv')

In [2]:
data_train.head()

,id,target,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
0,7,0,2,2,5,1,0,0,1,0,...,9,1,5,8,0,1,1,0,0,1
1,9,0,1,1,7,0,0,0,0,1,...,3,1,1,9,0,1,1,0,1,0
2,13,0,5,4,9,1,0,0,0,1,...,4,2,7,7,0,1,1,0,1,0
3,16,0,0,1,2,0,0,1,0,0,...,2,2,4,9,0,0,0,0,0,0
4,17,0,0,2,0,1,0,1,0,0,...,3,1,1,3,0,0,0,1,1,0

In [3]:
data_test.head()

,id,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,ps_ind_09_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
0,0,0,1,8,1,0,0,1,0,0,...,1,1,1,12,0,1,1,0,0,1
1,1,4,2,5,1,0,0,0,0,1,...,2,0,3,10,0,0,1,1,0,1
2,2,5,1,3,0,0,0,0,0,1,...,4,0,2,4,0,0,0,0,0,0
3,3,0,1,6,0,0,1,0,0,0,...,5,1,0,5,1,0,1,0,0,0
4,4,5,1,7,0,0,0,0,0,1,...,4,0,0,4,0,1,1,0,0,1

In [4]:
##Check for data info

#data_train.isnull()
#data_test.isnull()
#data_train.describe()
#data_test.describe()
#data_train.info()
data_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892816 entries, 0 to 892815
Data columns (total 58 columns):
id                892816 non-null int64
ps_ind_01         892816 non-null int64
ps_ind_02_cat     892816 non-null int64
ps_ind_03         892816 non-null int64
ps_ind_04_cat     892816 non-null int64
ps_ind_05_cat     892816 non-null int64
ps_ind_06_bin     892816 non-null int64
ps_ind_07_bin     892816 non-null int64
ps_ind_08_bin     892816 non-null int64
ps_ind_09_bin     892816 non-null int64
ps_ind_10_bin     892816 non-null int64
ps_ind_11_bin     892816 non-null int64
ps_ind_12_bin     892816 non-null int64
ps_ind_13_bin     892816 non-null int64
ps_ind_14         892816 non-null int64
ps_ind_15         892816 non-null int64
ps_ind_16_bin     892816 non-null int64
ps_ind_17_bin     892816 non-null int64
ps_ind_18_bin     892816 non-null int64
ps_reg_01         892816 non-null float64
ps_reg_02         892816 non-null float64
ps_reg_03         892816 non-null float64
ps_car_01_cat     892816 non-null int64
ps_car_02_cat     892816 non-null int64
ps_car_03_cat     892816 non-null int64
ps_car_04_cat     892816 non-null int64
ps_car_05_cat     892816 non-null int64
ps_car_06_cat     892816 non-null int64
ps_car_07_cat     892816 non-null int64
ps_car_08_cat     892816 non-null int64
ps_car_09_cat     892816 non-null int64
ps_car_10_cat     892816 non-null int64
ps_car_11_cat     892816 non-null int64
ps_car_11         892816 non-null int64
ps_car_12         892816 non-null float64
ps_car_13         892816 non-null float64
ps_car_14         892816 non-null float64
ps_car_15         892816 non-null float64
ps_calc_01        892816 non-null float64
ps_calc_02        892816 non-null float64
ps_calc_03        892816 non-null float64
ps_calc_04        892816 non-null int64
ps_calc_05        892816 non-null int64
ps_calc_06        892816 non-null int64
ps_calc_07        892816 non-null int64
ps_calc_08        892816 non-null int64
ps_calc_09        892816 non-null int64
ps_calc_10        892816 non-null int64
ps_calc_11        892816 non-null int64
ps_calc_12        892816 non-null int64
ps_calc_13        892816 non-null int64
ps_calc_14        892816 non-null int64
ps_calc_15_bin    892816 non-null int64
ps_calc_16_bin    892816 non-null int64
ps_calc_17_bin    892816 non-null int64
ps_calc_18_bin    892816 non-null int64
ps_calc_19_bin    892816 non-null int64
ps_calc_20_bin    892816 non-null int64
dtypes: float64(10), int64(48)
memory usage: 395.1 MB

In [5]:
y = data_train[['target']]
y.head()

   target
0       0
1       0
2       0
3       0
4       0

In [6]:
X = data_train.drop(['target'],axis=1)
X.head()

,id,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,ps_ind_09_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
0,7,2,2,5,1,0,0,1,0,0,...,9,1,5,8,0,1,1,0,0,1
1,9,1,1,7,0,0,0,0,1,0,...,3,1,1,9,0,1,1,0,1,0
2,13,5,4,9,1,0,0,0,1,0,...,4,2,7,7,0,1,1,0,1,0
3,16,0,1,2,0,0,1,0,0,0,...,2,2,4,9,0,0,0,0,0,0
4,17,0,2,0,1,0,1,0,0,0,...,3,1,1,3,0,0,0,1,1,0

In [7]:
# 随机生成8万个样本，用于二分类训练
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomTreesEmbedding, RandomForestClassifier, GradientBoostingClassifier, GradientBoostingRegressor
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_curve, auc, roc_auc_score
from sklearn.pipeline import make_pipeline

n_estimator = 10
# 将样本集分成测试集和训练集
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5)
X_train, X_train_lr, y_train, y_train_lr = train_test_split(X_train, y_train, test_size=0.5)

# 基于GBDT监督变换
grd = GradientBoostingClassifier(n_estimators=n_estimator)
grd.fit(X_train, y_train)
# 得到OneHot编码
grd_enc = OneHotEncoder(categories='auto')

temp = grd.apply(X_train)
np.set_printoptions(threshold=np.inf)  
grd_enc.fit(grd.apply(X_train)[:, :, 0])
#print(grd_enc.get_feature_names()) # 查看每一列对应的特征
# 使用OneHot编码作为特征，训练LR
grd_lm = LogisticRegression(solver='lbfgs', max_iter=1000)
grd_lm.fit(grd_enc.transform(grd.apply(X_train_lr)[:, :, 0]), y_train_lr)
# 使用LR对train_lr进行预测
y_pred_grd_lm = grd_lm.predict_proba(grd_enc.transform(grd.apply(X_test)[:, :, 0]))[:, 1]
fpr_grd_lm, tpr_grd_lm, _ = roc_curve(y_test, y_pred_grd_lm)
auc = roc_auc_score(y_test, y_pred_grd_lm)
print('LogisticRegression: ', auc)

# 使用GDBT-LR对test进行预测
test_pre = grd_lm.predict_proba(grd_enc.transform(grd.apply(data_test)[:, :, 0]))[:, 1]
print(test_pre)
test_pre.tofile('sample_submission.csv',sep=' ',format='%s')

/opt/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression:  0.6192225725471627

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)